volumes:
  mongodb:

services:

  mongo-db:
    image: mongo:8.2.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  incident-agent:
    build: ./agent
    container_name: incident-agent
    env_file:
      - agent/.env 
    depends_on:
      - mongo-db
      - incident-management-mcp
    ports:
      - "8000:8000"
    restart: unless-stopped

  incident-management-mcp:
    build: ./mcp
    env_file:
      - mcp/.env 
    ports:
      - "9000:9000"
    depends_on:
      - mongo-db