volumes:
  mongodb:

services:

  mongo-db:
    image: mongo:8.2.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  incident-agent:
    build: .
    container_name: incident-agent
    env_file:
      - .env 
    depends_on:
      - mongo-db
    ports:
      - "8000:8000"
    restart: unless-stopped